name: Haskell
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10", "8.8"]
    name: Haskell GHC ${{ matrix.ghc }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: lentille

      - name: Checkout monocle repo
        uses: actions/checkout@v2
        with:
          repository: change-metrics/monocle
          path: monocle
          # ref: refs/heads/master
          # To validate a PR with a dependent PR on Monocle
          ref: refs/pull/366/head

      - uses: haskell/actions/setup@v1
        with:
          cabal-version: "3.4"
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal','**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
            ${{ runner.os }}-
      - run: cabal update
      - run: cd lentille; cabal build --enable-tests all
      - run: cd lentille; cabal test --enable-tests --test-show-details=direct all
